### ISSUE TITLE
Propuesta: añadir columna en criterio.Todos (incertidumbre)

### ISSUE THREAD

**Issue by juliabaroon** [juliabaroon/TrabajoTDGrupo1#1]
Añadir una columna adicional en la función "criterio.Todos" de los métodos de incertidumbre, que contabilice cuántas veces ha sido la mejor en los métodos de incertidumbre (de los 6 disponibles).

**Comment by clagarbar3** [comment]
Buena idea. He realizado el cambio, así será más sencillo determinar  que alternativa es la elegida según el número de criterios para el que es óptimo. 
Se me ocurre que quizás sea buena idea poner al pie de la columna **que alternativa resulta óptima finalmente**, es decir, cuál tiene el conteo mas alto, y así agilizar el razonamiento del que aplique la función. ¿Que te parece?

**Comment by juliabaroon** [comment]
Perfecto. He añadido lo que propusiste a la función y he creado un nuevo Rmarkdown para probarla con ejercicios de la relación.
Si te parece que todo está bien y no hace falta añadirle nada más,  actualizamos el README comentando los cambios.

**Comment by clagarbar3** [comment]
Genial, yo me encargo de redactarlo.
