### ISSUE TITLE
Problemas al leer el problema 5

### ISSUE THREAD

**Issue by Anagi15** [juliabaroon/TrabajoTDGrupo1#11]
Cuando haces Run en el problema 5 no salen las soluciones de criterio.todos

**Comment by juliabaroon** [comment]
A mí sí me sale. Asegúrate antes de cargar la librería kableExtra.

**Comment by cristobalmc29** [comment]
A mí también Ana, probablemente sea por lo que ha dicho Julia.

**Comment by alvbonleo** [comment]
También lo he probado y funciona perfectamente. Prueba a compilar el fichero 'problemaspropuestos.Rmd' para que puedas observar los resultados correspondientes a todos lo criterios y así puedas interpretarlo.

**Comment by Anagi15** [comment]
Gracias chicos, he probado cargando todos los comandos pero ha seguido sin cargar la tabla. Lo que tu dices Alvaro es de la única manera en que se ve la tabla de resultados final.
