### ISSUE TITLE
Asignación comentar funciones.

### ISSUE THREAD

**Issue by clagarbar3** [juliabaroon/TrabajoTDGrupo1#2]
Como el fichero _"funcionesincertidumbre.R"_ tiene **15 funciones**, todas ellas sin comentar, he pensado en hacer el reparto de tareas para que cada uno comente **3** de ellas, ¿Qué os parece?

**Comment by cristobalmc29** [comment]
Me parece bien, 
Como idea de reparto, al ser 15 funciones y 5 integrantes en el grupo, podríamos asignar las funciones en orden como el profesor publicó en la enseñanza la asignación de grupos.
Es decir, 1 2 3 4 5, 1 2 3 4 5, 1 2 3 4 5.

**Comment by clagarbar3** [comment]
Buena idea. Usando esa lista la asignación sale así: 

![image](https://user-images.githubusercontent.com/113537184/196907166-771e4199-37e3-4c48-9b92-a0107ca2284f.png)

**-FUNCIONES:**

_crea.tablaX_   JULIA

_which.min.general_ ALVARO

_which.max general_ CLAUDIA

_distanciaEuclidea_ ANA

_criterio.tablaX.ejemplos_ CRISTOBAL

_criterio.Wald_ JULIA

_criterio.Optimista_ ALVARO

_criterio.Hurwicz_ CLAUDIA

_criterio.Hurwicz.General_ ANA

_dibuja.criterio.Hurwicz_ CRISTOBAL

_dibuja.criterio.Hurwicz_intervalos_ JULIA

_criterio.Savage_ ALVARO

_criterio.Laplace_  CLAUDIA

_criterio.PuntoIdeal_ ANA

_Criterio.Todos_ CRISTOBAL
