### ISSUE TITLE
Error al calcular la alternativa óptima ejercicio 3

### ISSUE THREAD

**Issue by clagarbar3** [juliabaroon/TrabajoTDGrupo1#4]
@juliabaroon  Encontré un fallo en el cambio que añadiste al pie de la columna _"Veces Optimo"_ de la tabla asociada a la función _"criterio.Todos"_.

Para el resto de ejercicios el pie de la columna salía correctamente (indicaba que alternativa tenía mayor conteo), pero para el problema 3 del fabricante de coches, devuelve como alternativa óptima otra que no es la de mayor conteo.

El error se produce ejecutando el siguiente código:
_tabla3=crea.tablaX(c(24,19,10,16,
                      22,22,23,20,
                      23,23,21,15,
                      25,24,18,14),numalternativas=4,numestados=4)
rownames(tabla3)=c("Deportivo","Berlina","Monovolumen","Todo-terreno")_ #Omitiendo este comando de asignación de nombres el error se produce igual, asignando como óptima la alternativa d1 cuando realmente es la d2.
_criterio.Todos(tabla3,alfa=0.5,T)_

Adjunto foto del error:
![image](https://user-images.githubusercontent.com/113537184/197257321-dd1902b8-9453-4244-b6f4-53bb6a2b1d14.png)

**Comment by juliabaroon** [comment]
Ya está solucionado.
Adjunto foto:
![ej3](https://user-images.githubusercontent.com/113537202/197357660-6d437533-8c09-4fed-b23f-8589211c5e1a.png)
