### ISSUE TITLE
Conteo de la función criterio.Todos en caso de empate

### ISSUE THREAD

**Issue by juliabaroon** [juliabaroon/TrabajoTDGrupo1#5]
@clagarbar3 probando la función actualizada criterio.Todos, me he dado cuenta de que en caso de que dos o más alternativas resulten óptimas según un criterio, al hacer el conteo la función solo tiene en cuenta una de ellas.

Adjunto foto:
![empate](https://user-images.githubusercontent.com/113537202/197337411-744555e8-6da5-457b-a569-a6890885c401.png)

**Comment by clagarbar3** [comment]
Ya he solucionado el problema en cuanto a los empates. Ahora en la columna _"Veces Optimo"_  puede aparecer más de una alternativa con el mismo conteo, al igual que en el pie de la columna, que parecerán todas las alternativas con un mismo conteo separadas por comas.

Adjunto foto:
![image](https://user-images.githubusercontent.com/113537184/197346778-9044e8cf-00bc-4071-9501-77dcc0cc64ef.png)
