### ISSUE TITLE
Mejora en la función norma euclidea

### ISSUE THREAD

**Issue by Anagi15** [juliabaroon/TrabajoTDGrupo1#7]
La solución podría mostrar también cual es la dimensión de R en la que estamos trabajando.

**Comment by clagarbar3** [comment]
Eso complicaría más su uso posterior en los criterios, ya que al devolver más de una cosa (por ejemplo en formato lista, devolver la distancia y la dimensión como comentas) y necesitar solo la distancia, cada vez que queramos dichos valores deberíamos cogerlos con [[ ]], por lo tanto deberíamos cambiar el resto de funciones del script.

**Comment by Anagi15** [comment]
Ahh, tienes razón. Habría que modificar todas las funciones que la utilizan y claro tampoco es un tipo información que vayamos a usar.
