### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by juliabaroon** [juliabaroon/TrabajoTDGrupo1#9]
Estoy creando la viñeta para nuestro trabajo que explicará cómo funciona el paquete referente a las funciones de incertidumbre.
Me gustaría que me dijeseis si os gusta la estructura o cambiarías algo para poder continuar desarrollando la viñeta. La podéis visualizar en R, pero os dejo aquí una foto:

![viñeta](https://user-images.githubusercontent.com/113537202/199251495-6544500c-18ab-4759-b450-e59f6e9a3f82.png)

**Comment by clagarbar3** [comment]
Me parece muy buena estructura. Para cada función añadiría además del propio ejemplo orientativo, una lista con los argumentos que se le pueden proporcionar a cada función incluyendo, en caso de tenerlos, sus valores por defecto.

**Comment by Anagi15** [comment]
Considero que está todo muy bien explicado y queda bastante claro el desarrollo de su uso.
